backend:
  name: github
  repo: your-username/alhaibah_site
  branch: main

media_folder: "images1"
public_folder: "/images1"

collections:
  - name: "gallery"
    label: "معرض الصور"
    file: "gallery.json"
    fields:
      - label: "صور المعرض"
        name: "items"
        widget: "list"
        summary: "{{fields.title}}"
        fields:
          - { label: "عنوان", name: "title", widget: "string" }
          - { label: "الصورة", name: "image", widget: "image" }