backend:
  name: github
  repo: husam128/alnabntsite
  branch: main
  auth_type: implicit

media_folder: "images1"
public_folder: "/images1"

collections:
  - name: "gallery"
    label: "Gallery"  # تغيير من "import" إلى اسم أوضح
    folder: "content/gallery"
    create: true
    slug: "{{slug}}"  # تصحيح قيمة slug
    fields:
      - {label: "Title", name: "title", widget: "string" }  
      - label: "Items"
        name: "items"
        widget: "list"
        summary: "{{fields.title}}"  # تصحيح بناء الجملة
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
